package com.ds4h.scratchradiomics.features;

import ij.ImagePlus;
import ij.gui.Roi;
import ij.process.ImageProcessor;
import ij.process.ImageStatistics;

import java.awt.Polygon;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class IbsiFeatureExtractor {

    /**
     * Extracts IBSI-compliant radiomic features (Morphological and First-Order Intensity)
     * from a specific ROI in an ImagePlus image.
     *
     * @param imp The active ImagePlus image
     * @param roi The segmented ROI (e.g., generated by SAM)
     * @return A map containing feature name–value pairs (FeatureName -> ComputedValue)
     */
    public static Map<String, Double> extractFeatures(ImagePlus imp, Roi roi) {
        final Map<String, Double> features = new HashMap<>();

        if (imp == null || roi == null) {
            System.err.println("[ScratchRadiomics] Image or ROI not valid for feature extraction.");
            return features;
        }

        imp.setRoi(roi);
        final ImageProcessor ip = imp.getProcessor();

        final float[] roiPixels = extractPixelsInsideRoi(ip, roi);

        if (roiPixels.length == 0) {
            System.err.println("[ScratchRadiomics] This ROI does not contains valid pixels.");
            return features;
        }

        extractMorphologicalFeatures(roi, imp, features);
        extractIntensityFeatures(roiPixels, features);

        return features;
    }

    /**
     * Calculate the 2D morphological features.
     */
    private static void extractMorphologicalFeatures(Roi roi, ImagePlus imp, Map<String, Double> features) {
        final double pixelWidth = imp.getCalibration().pixelWidth;
        final double pixelHeight = imp.getCalibration().pixelHeight;
        final double pixelAreaScale = pixelWidth * pixelHeight;

        final ImageStatistics stats = roi.getStatistics();
        final double areaPixels = stats.pixelCount;
        final double areaCalibrated = areaPixels * pixelAreaScale;

        final double perimeterCalibrated = roi.getLength() * pixelWidth;

        features.put("IBSI_2D_Area", areaCalibrated);

        features.put("IBSI_2D_Perimeter", perimeterCalibrated);

        final double equivalentDiameter = Math.sqrt((4.0 * areaCalibrated) / Math.PI);
        features.put("IBSI_2D_EquivalentDiameter", equivalentDiameter);

        final double circularity = (perimeterCalibrated > 0) ? (4.0 * Math.PI * areaCalibrated) / (perimeterCalibrated * perimeterCalibrated) : 0.0;
        features.put("IBSI_2D_Circularity", circularity);

        final Polygon convexHull = roi.getConvexHull();
        if (convexHull != null) {
            final Roi convexRoi = new ij.gui.PolygonRoi(convexHull, Roi.POLYGON);
            final double convexArea = convexRoi.getStatistics().pixelCount * pixelAreaScale;
            final double solidity = (convexArea > 0) ? areaCalibrated / convexArea : 1.0;
            features.put("IBSI_2D_Solidity", solidity);
        }
    }

    /**
     * Calculate the First-order Intensity Statistics.
     */
    private static void extractIntensityFeatures(float[] pixels, Map<String, Double> features) {
        final int n = pixels.length;
        if (n == 0) return;

        double sum = 0.0;
        double min = Double.MAX_VALUE;
        double max = -Double.MAX_VALUE;

        for (float p : pixels) {
            sum += p;
            if (p < min) min = p;
            if (p > max) max = p;
        }

        final double mean = sum / n;
        features.put("IBSI_Intensity_Mean", mean);

        features.put("IBSI_Intensity_Min", min);
        features.put("IBSI_Intensity_Max", max);

        double varianceSum = 0.0;
        double skewnessSum = 0.0;
        double kurtosisSum = 0.0;
        double rmsSum = 0.0;

        for (final float p : pixels) {
            final double diff = p - mean;
            varianceSum += diff * diff;
            skewnessSum += Math.pow(diff, 3);
            kurtosisSum += Math.pow(diff, 4);
            rmsSum += p * p;
        }

        final double variance = varianceSum / n;
        final double stdDev = Math.sqrt(variance);

        features.put("IBSI_Intensity_Variance", variance);
        features.put("IBSI_Intensity_StdDev", stdDev);

        final double rms = Math.sqrt(rmsSum / n);
        features.put("IBSI_Intensity_RMS", rms);

        final double skewness = (stdDev > 0) ? (skewnessSum / n) / Math.pow(stdDev, 3) : 0.0;
        features.put("IBSI_Intensity_Skewness", skewness);

        final double kurtosis = (stdDev > 0) ? ((kurtosisSum / n) / Math.pow(stdDev, 4)) - 3.0 : 0.0;
        features.put("IBSI_Intensity_ExcessKurtosis", kurtosis);

        Arrays.sort(pixels);

        final double median = getPercentile(pixels, 50);
        features.put("IBSI_Intensity_Median", median);

        features.put("IBSI_Intensity_P10", getPercentile(pixels, 10));
        features.put("IBSI_Intensity_P90", getPercentile(pixels, 90));

        final double iqr = getPercentile(pixels, 75) - getPercentile(pixels, 25);
        features.put("IBSI_Intensity_IQR", iqr);
    }

    /**
     * Extract the real values of intensity only in the pixel in the ROI perimeter.
     */
    private static float[] extractPixelsInsideRoi(ImageProcessor ip, Roi roi) {
        final java.awt.Rectangle bounds = roi.getBounds();
        int count = 0;

        for (int y = bounds.y; y < bounds.y + bounds.height; y++) {
            for (int x = bounds.x; x < bounds.x + bounds.width; x++) {
                if (roi.contains(x, y)) {
                    count++;
                }
            }
        }

        final float[] pixels = new float[count];
        int idx = 0;

        for (int y = bounds.y; y < bounds.y + bounds.height; y++) {
            for (int x = bounds.x; x < bounds.x + bounds.width; x++) {
                if (roi.contains(x, y)) {
                    pixels[idx++] = ip.getPixelValue(x, y);
                }
            }
        }

        return pixels;
    }

    /**
     * Calculate the percentile from an ordered float array.
     */
    private static double getPercentile(float[] sortedPixels, double percentile) {
        if (sortedPixels.length == 0) return 0.0;
        int index = (int) Math.ceil((percentile / 100.0) * sortedPixels.length) - 1;
        index = Math.max(0, Math.min(index, sortedPixels.length - 1));
        return sortedPixels[index];
    }
}
